// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[] args) {
		int limit = Integer.parseInt(args[0]);

		int countBelowHalf = 0;
		int countHalfAndAbove = 0;

		while (countBelowHalf + countHalfAndAbove < limit) {
			double random = Math.random();

			if (random < 0.5) {
				countBelowHalf++;
			} else {
				countHalfAndAbove++;
			}
		}

		System.out.println("> 0.5: " + countBelowHalf + " times");
		System.out.println("<= 0.5: " + countHalfAndAbove + " times");
	}
}
